// Code generated by MockGen. DO NOT EDIT.
// Source: organization.go
//
// Generated by this command:
//
//	mockgen -source=organization.go -destination=mock_organization.go -package=organization
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"

	"google.golang.org/api/cloudresourcemanager/v1"

	schema "github.com/cloudposse/atmos/pkg/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockcrmProjectsService is a mock of crmProjectsService interface.
type MockcrmProjectsService struct {
	ctrl     *gomock.Controller
	recorder *MockcrmProjectsServiceMockRecorder
	isgomock struct{}
}

// MockcrmProjectsServiceMockRecorder is the mock recorder for MockcrmProjectsService.
type MockcrmProjectsServiceMockRecorder struct {
	mock *MockcrmProjectsService
}

// NewMockcrmProjectsService creates a new mock instance.
func NewMockcrmProjectsService(ctrl *gomock.Controller) *MockcrmProjectsService {
	mock := &MockcrmProjectsService{ctrl: ctrl}
	mock.recorder = &MockcrmProjectsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcrmProjectsService) EXPECT() *MockcrmProjectsServiceMockRecorder {
	return m.recorder
}

// GetAncestry mocks base method.
func (m *MockcrmProjectsService) GetAncestry(projectID string, req *cloudresourcemanager.GetAncestryRequest) (*cloudresourcemanager.GetAncestryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAncestry", projectID, req)
	ret0, _ := ret[0].(*cloudresourcemanager.GetAncestryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAncestry indicates an expected call of GetAncestry.
func (mr *MockcrmProjectsServiceMockRecorder) GetAncestry(projectID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAncestry", reflect.TypeOf((*MockcrmProjectsService)(nil).GetAncestry), projectID, req)
}

// MockGetter is a mock of Getter interface.
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
	isgomock struct{}
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance.
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// GetOrganization mocks base method.
func (m *MockGetter) GetOrganization(ctx context.Context, atmosConfig *schema.AtmosConfiguration, gcpAuth *schema.GCPAuthContext) (*OrganizationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, atmosConfig, gcpAuth)
	ret0, _ := ret[0].(*OrganizationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockGetterMockRecorder) GetOrganization(ctx, atmosConfig, gcpAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockGetter)(nil).GetOrganization), ctx, atmosConfig, gcpAuth)
}
